version: "3.8"

services:
  backend:
    build: .
    container_name: goalup_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "ep-dry-silence-ai1wgg9u-pooler.c-4.us-east-1.aws.neon.tech:44.211.114.173"
    volumes:
      - .:/app
    restart: unless-stopped
