"""Add unique constraint for team and jersey number

Revision ID: 0026b0c6670d
Revises: e9fbe4cdabb4
Create Date: 2026-02-09 23:05:58.441230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0026b0c6670d'
down_revision: Union[str, None] = 'e9fbe4cdabb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'jersey_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # The enum was originally 'player_position', autogen tried to rename or mismatch it.
    # We'll just skip the enum alter if it's already there or fix the type reference.
    op.create_unique_constraint('unique_team_jersey', 'player', ['team_id', 'jersey_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_team_jersey', 'player', type_='unique')
    op.alter_column('player', 'jersey_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
