"""Add additional time fields to match

Revision ID: 0ab5b950f4e6
Revises: 8a51b9006fde
Create Date: 2026-02-10 14:35:13.295835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0ab5b950f4e6'
down_revision: Union[str, None] = '8a51b9006fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('additional_time_first_half', sa.Integer(), server_default='0', nullable=False))
    op.add_column('match', sa.Column('additional_time_second_half', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('match', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('scheduled', 'live', 'finished', name='matchstatus'),
               existing_nullable=False)
    op.alter_column('player', 'position',
               existing_type=postgresql.ENUM('cb', 'cdm', 'cam', 'cm', 'st', 'lw', 'rw', 'rb', 'lb', 'gk', name='player_position'),
               type_=sa.Enum('cb', 'cdm', 'cam', 'cm', 'st', 'lw', 'rw', 'rb', 'lb', 'gk', name='position'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'position',
               existing_type=sa.Enum('cb', 'cdm', 'cam', 'cm', 'st', 'lw', 'rw', 'rb', 'lb', 'gk', name='position'),
               type_=postgresql.ENUM('cb', 'cdm', 'cam', 'cm', 'st', 'lw', 'rw', 'rb', 'lb', 'gk', name='player_position'),
               nullable=True)
    op.alter_column('match', 'status',
               existing_type=sa.Enum('scheduled', 'live', 'finished', name='matchstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('match', 'additional_time_second_half')
    op.drop_column('match', 'additional_time_first_half')
    # ### end Alembic commands ###
