"""Add color to team

Revision ID: 8a51b9006fde
Revises: 0026b0c6670d
Create Date: 2026-02-10 01:21:57.868595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
"""Add color to team

Revision ID: 8a51b9006fde
Revises: 0026b0c6670d
Create Date: 2026-02-10 01:21:57.868595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a51b9006fde'
down_revision: Union[str, None] = '0026b0c6670d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'color')
    # ### end Alembic commands ###
