"""Add jersey_number and position to player

Revision ID: e9fbe4cdabb4
Revises: 
Create Date: 2026-02-09 22:47:17.275263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e9fbe4cdabb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the type first
    op.execute("CREATE TYPE player_position AS ENUM ('cb', 'cdm', 'cam', 'cm', 'st', 'lw', 'rw', 'rb', 'lb', 'gk')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('jersey_number', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('position', sa.Enum('cb', 'cdm', 'cam', 'cm', 'st', 'lw', 'rw', 'rb', 'lb', 'gk', name='player_position'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'position')
    op.drop_column('player', 'jersey_number')
    # ### end Alembic commands ###
    # Drop the type
    op.execute("DROP TYPE player_position")
