"""Add total_time to match

Revision ID: fdea4fe1ef4f
Revises: 0ab5b950f4e6
Create Date: 2026-02-10 15:01:08.823462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdea4fe1ef4f'
down_revision: Union[str, None] = '0ab5b950f4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('total_time', sa.Integer(), server_default='90', nullable=False))
    op.alter_column('match', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('scheduled', 'live', 'finished', name='matchstatus'),
               existing_nullable=False)
    op.alter_column('player', 'position',
               existing_type=postgresql.ENUM('cb', 'cdm', 'cam', 'cm', 'st', 'lw', 'rw', 'rb', 'lb', 'gk', name='player_position'),
               type_=sa.Enum('cb', 'cdm', 'cam', 'cm', 'st', 'lw', 'rw', 'rb', 'lb', 'gk', name='position'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'position',
               existing_type=sa.Enum('cb', 'cdm', 'cam', 'cm', 'st', 'lw', 'rw', 'rb', 'lb', 'gk', name='position'),
               type_=postgresql.ENUM('cb', 'cdm', 'cam', 'cm', 'st', 'lw', 'rw', 'rb', 'lb', 'gk', name='player_position'),
               nullable=True)
    op.alter_column('match', 'status',
               existing_type=sa.Enum('scheduled', 'live', 'finished', name='matchstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('match', 'total_time')
    # ### end Alembic commands ###
